language: android
jdk:
    - oraclejdk8
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.0

    # The SDK version used to compile your project
    - android-25

    # Additional components
    # - addon
    # - extra
    
script:
    - ./gradlew build
    
before_install:
    - openssl aes-256-cbc -K $encrypted_48b17afb67f0_key -iv $encrypted_48b17afb67f0_iv -in travis_ci_secrets.tar.enc -out travis_ci_secrets.tar -d
    - tar xvf travis_ci_secrets.tar